package entidades.appMonjarrez;

import entidades.DatabaseConnection;
import entidades.Usuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.WindowEvent;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmIniciarSesion extends javax.swing.JFrame {
    FondoSesion fondo = new FondoSesion();
    Usuario oUsuario;
    FrmTablaUsuario oFrmTablaUsuario = new FrmTablaUsuario();
    private int intentos = 0;

    /**
     * Creates new form FrmIniciarSesion
     */
    public FrmIniciarSesion() {
        setContentPane(fondo);
        initComponents();

        bntCodigoInicioSesion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMonjarrez = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        lblHeolvodadoContraseña = new javax.swing.JLabel();
        btnSI = new javax.swing.JButton();
        bntCodigoInicioSesion = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        lblMonjarrez.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblMonjarrez.setForeground(new java.awt.Color(204, 0, 0));
        // lblMonjarrez.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/facebook-verificado.png")));
        // // NOI18N
        lblMonjarrez.setText("Monjarrez");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMonjarrez, javax.swing.GroupLayout.PREFERRED_SIZE, 271,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMonjarrez)
                                .addContainerGap()));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblIniciarSesion.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setText("Iniciar sesión");

        txtCorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setToolTipText("Para iniciar sesión, por favor ingrese los datos de su cuenta ya creada.");
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Correo electrónico",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
        });

        txtContraseña.setBackground(new java.awt.Color(0, 0, 0));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)),
                "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11),
                new java.awt.Color(255, 255, 255))); // NOI18N

        btnIniciarSesion.setBackground(new java.awt.Color(204, 0, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión ");
        btnIniciarSesion
                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lblHeolvodadoContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lblHeolvodadoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblHeolvodadoContraseña.setText("¿Te olvidaste de tu contraseña?");

        btnSI.setBackground(new java.awt.Color(0, 0, 0));
        btnSI.setForeground(new java.awt.Color(255, 255, 255));
        btnSI.setText("Sí");
        btnSI.setToolTipText("Haz clic en el botón para activar otra función.");
        btnSI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIActionPerformed(evt);
            }
        });

        bntCodigoInicioSesion.setBackground(new java.awt.Color(0, 0, 0));
        bntCodigoInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        bntCodigoInicioSesion.setText("Utilizar código de inicio de sesión");
        bntCodigoInicioSesion
                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bntCodigoInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCodigoInicioSesionActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Atrás");
        jButton4.setToolTipText("Presiona el botón para regresar al menú principal.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(lblIniciarSesion)
                                                        .addComponent(txtCorreo)
                                                        .addComponent(txtContraseña,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 440,
                                                                Short.MAX_VALUE)
                                                        .addComponent(btnIniciarSesion,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(223, 223, 223)
                                                .addComponent(btnSI, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(lblHeolvodadoContraseña,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 174,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(144, 144, 144)
                                                .addComponent(bntCodigoInicioSesion,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 233,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(42, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblIniciarSesion)
                                .addGap(42, 42, 42)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHeolvodadoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSI, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntCodigoInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26,
                                        Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(558, 558, 558)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(458, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void btnSIActionPerformed(java.awt.event.ActionEvent evt) {
        bntCodigoInicioSesion.setEnabled(true);
    }

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {

        if (txtCorreo.getText().equals("Escriba su correo")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.WHITE);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        formWindowClosing(new WindowEvent(this, 0));

    }

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (txtCorreo.getText().isEmpty() || txtContraseña.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Estimado Usuario. Debe digitar sus datos de Inicio para acceder a su cuenta");
                return;
            }

            String correo = txtCorreo.getText();
            String contraseña = txtContraseña.getText();
            String hashedPassword = hashContraseña(contraseña); // Hashear la contraseña ingresada

            // Conectar a la base de datos
            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "SELECT * FROM Usuarios WHERE correo = ? AND contraseña = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, correo);
                    pstmt.setString(2, hashedPassword);

                    try (ResultSet rs = pstmt.executeQuery()) {
                        if (rs.next()) {
                            // Si se encuentra un usuario con las credenciales correctas
                            JOptionPane.showMessageDialog(this, "Inicio de sesión exitosa");
                            JOptionPane.showMessageDialog(this, "Bienvenido!!");

                            FrmEmpresa oFrmEmpresa = new FrmEmpresa();
                            oFrmEmpresa.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            oFrmEmpresa.setVisible(true);

                            intentos = 0;
                            this.dispose();
                        } else {
                            // Si no se encuentra el usuario
                            JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Intente nuevamente.");
                            txtCorreo.setText("");
                            txtContraseña.setText("");

                            intentos++;
                            if (intentos >= 3) {
                                JOptionPane.showMessageDialog(null,
                                        "Lo sentimos, se han agotado los intentos. El programa se cerrará.");
                                this.dispose();
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error durante el inicio de sesión: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void bntCodigoInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {

        // String correo = txtCorreo.getText();
        // Enviar codigo para ingresar usando la lista y comparando si hay un correo
        // igual y si esta el correo
        // regjistrado se envia el
        JOptionPane.showMessageDialog(this, "Lo sentimos.Esta opcion no se encuentra habilitada en este momento");

    }

    // Método simulado para "hash" de la contraseña
    private String hashContraseña(String contraseña) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(contraseña.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1)
                    hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {

        int respuesta = JOptionPane.showConfirmDialog(this, "Desea abandonar el área de inicio de sesión?",
                "Atención", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bntCodigoInicioSesion;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnSI;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHeolvodadoContraseña;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblMonjarrez;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration
}

class FondoSesion extends JPanel {
    private ImageIcon sesion;

    public FondoSesion() {
        // Cargar la imagen de fondo
        sesion = new ImageIcon(
                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\download~3.jpg");
        if (sesion.getImageLoadStatus() != MediaTracker.COMPLETE) {
            System.err.println("Error al cargar la imagen de fondo.");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (sesion != null) {
            g.drawImage(sesion.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    }
}
