package entidades.appMonjarrez;

import java.awt.Graphics;
import java.awt.MediaTracker;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmMenuMonjarrez extends javax.swing.JFrame {
    FondoMenu fondo = new FondoMenu();

    /**
     * Creates new form FrmMenuMonjarrez
     */
    public FrmMenuMonjarrez() {
        setContentPane(fondo);
        initComponents();
        // btnIngresar.setEnabled(false);

        btnComprador.setContentAreaFilled(false);
        btnComprador.setBorderPainted(true);
        btnComprador.setOpaque(false);
        btnComprador.setFocusPainted(false);

        btnInvitado.setContentAreaFilled(false);
        btnInvitado.setBorderPainted(true);
        btnInvitado.setOpaque(false);
        btnInvitado.setFocusPainted(false);

        btnAdministrador.setContentAreaFilled(false);
        btnAdministrador.setBorderPainted(true);
        btnAdministrador.setOpaque(false);
        btnAdministrador.setFocusPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jpnlMenu = new javax.swing.JPanel();
        btnVendedor = new javax.swing.JButton();
        btnComprador = new javax.swing.JButton();
        btnInvitado = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlMenu.setBackground(new java.awt.Color(0, 0, 0));

        btnVendedor.setBackground(new java.awt.Color(51, 51, 0));
        btnVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnVendedor.setForeground(new java.awt.Color(0, 0, 0));
        // btnVendedor.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/rendimiento.png")));
        // // NOI18N
        btnVendedor.setText("Vendedor");
        btnVendedor.setToolTipText("¡Lleva tu emprendimiento al siguiente nivel!");
        btnVendedor
                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        btnComprador.setForeground(new java.awt.Color(255, 255, 255));
        // btnComprador.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/comprador.png")));
        // // NOI18N
        btnComprador.setText("Comprador");
        btnComprador.setToolTipText("¡Haz tus compras favoritas desde la comodidad de tu Casa!");
        btnComprador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompradorActionPerformed(evt);
            }
        });

        btnInvitado.setForeground(new java.awt.Color(255, 255, 255));
        // btnInvitado.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/estrella-invitada.png")));
        // // NOI18N
        btnInvitado.setText("Invitado");
        btnInvitado.setToolTipText("¡Visítanos y descubre más sobre nosotros!");
        btnInvitado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadoActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        // jButton4.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/cerrar-sesion
        // (2).png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.setToolTipText("Salir del sistema");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        // jLabel3.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/sonriente.png")));
        // // NOI18N
        jLabel3.setToolTipText("¡Esperamos que estés disfrutando de nuestra aplicación!");

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrarme como...");

        javax.swing.GroupLayout jpnlMenuLayout = new javax.swing.GroupLayout(jpnlMenu);
        jpnlMenu.setLayout(jpnlMenuLayout);
        jpnlMenuLayout.setHorizontalGroup(
                jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnVendedor, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnComprador, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnInvitado, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 446,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMenuLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)));
        jpnlMenuLayout.setVerticalGroup(
                jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48,
                                        Short.MAX_VALUE)
                                .addComponent(btnVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButton4)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        // jLabel1.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/facebook-verificado.png")));
        // // NOI18N
        jLabel1.setText("Monjarrez");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        btnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        // btnIngresar.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/ingresar.png")));
        // // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("Haz clic aquí para iniciar sesión si ya tienes una cuenta!");
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnAdministrador.setBackground(new java.awt.Color(51, 51, 51));
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
       // btnAdministrador
                //.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/configuraciones.png"))); // NOI18N
        btnAdministrador.setText("Administrador");
        btnAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(504, Short.MAX_VALUE)
                                .addComponent(jpnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(507, 507, 507)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jpnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        555, Short.MAX_VALUE)
                                                .addComponent(btnAdministrador)))
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas Salir del programa?", "Confirmar Salir",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Gracias por Visitarnos...");
            System.exit(0);
        }

    }

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {

        String clave;
        int intentos = 0;
        boolean claveValida = false;

        while (intentos < 3 && !claveValida) {

            clave = JOptionPane.showInputDialog(" Señor usuario ingrese su clave:");

            if (clave == null || clave.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Programa cerrado.");
                return;
            }

            if (esClaveValida(clave)) {
                JOptionPane.showMessageDialog(null, "ingresando..... " + clave);
                claveValida = true;

                MDI_MenuMonjarrez oMDI_MenuMonjarrez = new MDI_MenuMonjarrez();

                oMDI_MenuMonjarrez.setExtendedState(JFrame.MAXIMIZED_BOTH);

                oMDI_MenuMonjarrez.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Clave inválida. Intente nuevamente.");
                intentos++;
            }
        }

        if (!claveValida) {
            JOptionPane.showMessageDialog(null, "Lo sentimos se han agotado los intentos, El programa se cerrará.");
        }

    }

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {
        FrmIniciarSesion oFrmIniciarSesion = new FrmIniciarSesion();

        oFrmIniciarSesion.setExtendedState(JFrame.MAXIMIZED_BOTH);

        oFrmIniciarSesion.setVisible(true);
    }

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {

        JOptionPane.showMessageDialog(this, "Primero, regístrate como usuario de la aplicación");

        FrmRegistrarVendedor oFrmRegistrarUsuario = new FrmRegistrarVendedor(TipoMantenimiento.AGREGAR, null);

        oFrmRegistrarUsuario.setExtendedState(JFrame.MAXIMIZED_BOTH);

        oFrmRegistrarUsuario.setVisible(true);

    }

    private void btnCompradorActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Primero, regístrate como usuario de la aplicación");

        FrmRegistrarComprador oFrmRegistrarComp = new FrmRegistrarComprador(TipoMantenimiento.AGREGAR, null);

        oFrmRegistrarComp.setExtendedState(JFrame.MAXIMIZED_BOTH);

        oFrmRegistrarComp.setVisible(true);

        btnIngresar.setEnabled(true);

    }

    private void btnInvitadoActionPerformed(java.awt.event.ActionEvent evt) {

        JOptionPane.showMessageDialog(this, "Primero, regístrate como usuario de la aplicación");

        FrmRegistrarInvitado oFrmFrmRegistrarInvitado = new FrmRegistrarInvitado(TipoMantenimiento.AGREGAR, null);

        oFrmFrmRegistrarInvitado.setExtendedState(JFrame.MAXIMIZED_BOTH);

        oFrmFrmRegistrarInvitado.setVisible(true);
        btnIngresar.setEnabled(true);

    }

    private static boolean esClaveValida(String clave) {

        int[] digitos = new int[4];
        for (int i = 0; i < 4; i++) { // 0-3
            digitos[i] = Character.getNumericValue(clave.charAt(i));

            if (digitos[i] < 0 || digitos[i] > 9) {
                return false;
            }
        }

        /**
         * cada dígito sea el doble del anterior
         * se toma el dijito anterior i-1 % digito de unidades
         * Verificamos que la clave tenga 4 dígitos
         */

        int claveEsperada;
        for (int i = 1; i < 4; i++) {
            claveEsperada = (digitos[i - 1] * 2) % 10;
            if (digitos[i] != claveEsperada) {
                return false;
            }
        }

        if (clave.length() != 4) {
            return false;
        }

        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuMonjarrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnComprador;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpnlMenu;
    // End of variables declaration
}

class FondoMenu extends JPanel {
    private ImageIcon menu;

    public FondoMenu() {

        menu = new ImageIcon(
                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-ECJZYwYmswAfHse2zy2CFj (1)~2.jpg");
        if (menu.getImageLoadStatus() != MediaTracker.COMPLETE) {
            System.err.println("Error al cargar la imagen de fondo.");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (menu != null) {
            g.drawImage(menu.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    }

}