package entidades.appMonjarrez;

import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import entidades.Utilidades.UtilidadesImagen;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmPrincipalMonjarrez extends javax.swing.JFrame {
        FondoPrincipal fondo = new FondoPrincipal();
        private JLabel etiquetaImagen;
       

        /**
         * Creates new form FrmPrincipalMonjarrez
         */
        public FrmPrincipalMonjarrez() {

                setContentPane(fondo);
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                setLayout(null);

                etiquetaImagen = new JLabel();
                int anchoImagen = 500;
                int altoImagen = 500;

                ImageIcon icono = UtilidadesImagen.redimensionarImagen(
                                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\Polish_20250226_191728811.png",
                                anchoImagen,
                                altoImagen);
                if (icono != null) {
                        etiquetaImagen.setIcon(icono);
                        etiquetaImagen.setSize(anchoImagen, altoImagen);

                        add(etiquetaImagen);

                        setExtendedState(JFrame.MAXIMIZED_BOTH);
                        setVisible(true);

                        centrarEtiquetaImagen();

                        addComponentListener(new ComponentAdapter() {
                                @Override
                                public void componentResized(ComponentEvent e) {
                                        centrarEtiquetaImagen();
                                }
                        });

                        fondo.repaint();
                } else {
                        System.err.println("No se pudo cargar la imagen.");
                        JOptionPane.showMessageDialog(null, "No se pudo cargar la imagen");
                }

                initComponents();
        }

        private void centrarEtiquetaImagen() {
                int anchoImagen = etiquetaImagen.getWidth();
                int altoImagen = etiquetaImagen.getHeight();
                int x = (getWidth() - anchoImagen) / 2;
                int y = (getHeight() - altoImagen) / 2;
                etiquetaImagen.setBounds(x, y, anchoImagen, altoImagen);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                BtnIngresar = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                BtnIngresar.setBackground(new java.awt.Color(0, 0, 0));
                BtnIngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
                // BtnIngresar.setIcon(
                //                 new javax.swing.ImageIcon(getClass().getResource(
                //                                 "C:/proyecto_Iván_E/entidades/imagenes/circulo.png"))); // NOI18N
                BtnIngresar.setText("Ingresar");
                BtnIngresar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¡Vive una nueva experiencia!",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
                BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BtnIngresarActionPerformed(evt);
                        }
                });

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));

                jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(204, 0, 0));
                // jLabel1.setIcon(
                //                 new javax.swing.ImageIcon(
                //                                 getClass().getResource("/entidades/imagenes/facebook-verificado.png"))); // NOI18N
                jLabel1.setText("Monjarrez ");
                jLabel1.setToolTipText("¡Estamos aquí para hacer tu experiencia aún mejor!");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                276,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 13, Short.MAX_VALUE)));

                jPanel2.setBackground(new java.awt.Color(0, 0, 0));

                jLabel2.setFont(new java.awt.Font("Dialog", 2, 48)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("My virtual store...");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                65,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(550, Short.MAX_VALUE)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(349, 349, 349)
                                                                .addComponent(BtnIngresar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                178,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                412,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(BtnIngresar,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                68,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {
                FrmMenuMonjarrez FrmMenuMonjarrez = new FrmMenuMonjarrez();

                FrmMenuMonjarrez.setExtendedState(JFrame.MAXIMIZED_BOTH);

                FrmMenuMonjarrez.setVisible(true);

                this.dispose();
        }

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify
        private javax.swing.JButton BtnIngresar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration
}

class FondoPrincipal extends JPanel {
        private ImageIcon fondoIcono;

        public FondoPrincipal() {
                // Cargar la imagen de fondo
                fondoIcono = new ImageIcon(
                                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-ECJZYwYmswAfHse2zy2CFj (1)~2.jpg");
                if (fondoIcono.getImageLoadStatus() != MediaTracker.COMPLETE) {
                        System.err.println("Error al cargar la imagen de fondo.");
                }
        }

        @Override
        protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (fondoIcono != null) {
                        g.drawImage(fondoIcono.getImage(), 0, 0, getWidth(), getHeight(), this);
                }
        }
}

