package entidades.appMonjarrez;

import entidades.PersistenciaUsuario.PersistenciaUsuarioTabla;
import static entidades.PersistenciaUsuario.PersistenciaUsuarioTabla.generarNuevoId;

import entidades.DatabaseConnection;
import entidades.Usuario;
import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmRegistrarInvitado extends javax.swing.JFrame {
        FondoInvitado fondo = new FondoInvitado();
        Usuario oUsuario;
        TipoMantenimiento oTipo;

        /**
         * Creates new form FrmRegistrarInvitado
         */
        public FrmRegistrarInvitado(TipoMantenimiento tipo, Usuario oUsuario) {
                setContentPane(fondo);
                initComponents();

                this.oTipo = tipo;
                this.oUsuario = oUsuario;

                switch (tipo) {
                        case AGREGAR:
                                // Configuración para agregar
                                txtNombreI.setEnabled(true);
                                txtCorreoI.setEnabled(true);
                                txtContraseñaI.setEnabled(true);
                                break;
                        case MODIFICAR:
                                // Configuración para modificar
                                txtNombreI.setText(oUsuario.getNombre());
                                txtCorreoI.setText(oUsuario.getCorreo());
                                txtContraseñaI.setText(oUsuario.getContraseña());
                                txtNombreI.setEnabled(true);
                                txtCorreoI.setEnabled(true);
                                txtContraseñaI.setEnabled(true);
                                break;
                        default:
                                break;
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                lblCorreo1 = new javax.swing.JPanel();
                lblRegistrarme1 = new javax.swing.JLabel();
                lblNombre1 = new javax.swing.JLabel();
                txtNombreI = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtCorreoI = new javax.swing.JTextField();
                lblContraseña1 = new javax.swing.JLabel();
                txtContraseñaI = new javax.swing.JTextField();
                btnAceptarI = new javax.swing.JButton();
                btnCancelar1 = new javax.swing.JButton();
                btnAtras1 = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));
                jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                jLabel2.setBackground(new java.awt.Color(0, 0, 0));
                jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(204, 0, 0));
                // jLabel2.setIcon(new
                // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/facebook-verificado.png")));
                // // NOI18N
                jLabel2.setText("Monjarrez");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                296,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                61, Short.MAX_VALUE)
                                                                .addContainerGap()));

                lblCorreo1.setBackground(new java.awt.Color(0, 0, 0));

                lblRegistrarme1.setBackground(new java.awt.Color(255, 255, 255));
                lblRegistrarme1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                lblRegistrarme1.setForeground(new java.awt.Color(255, 255, 255));
                lblRegistrarme1.setText("Registrarme");

                lblNombre1.setBackground(new java.awt.Color(0, 0, 0));
                lblNombre1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
                lblNombre1.setText("Nombre");

                txtNombreI.setBackground(new java.awt.Color(0, 0, 0));
                txtNombreI.setForeground(new java.awt.Color(255, 255, 255));
                txtNombreI.setToolTipText("\"Señor usuario, por favor ingrese su primer nombre para registrarse.");
                txtNombreI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                jLabel5.setBackground(new java.awt.Color(0, 0, 0));
                jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Correo");

                txtCorreoI.setBackground(new java.awt.Color(0, 0, 0));
                txtCorreoI.setForeground(new java.awt.Color(255, 255, 255));
                txtCorreoI.setToolTipText(
                                "Por favor, ingrese su correo electrónico personal o el que usa con más frecuencia.");
                txtCorreoI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                lblContraseña1.setBackground(new java.awt.Color(0, 0, 0));
                lblContraseña1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                lblContraseña1.setForeground(new java.awt.Color(255, 255, 255));
                lblContraseña1.setText("Contraseña");

                txtContraseñaI.setBackground(new java.awt.Color(0, 0, 0));
                txtContraseñaI.setForeground(new java.awt.Color(255, 255, 255));
                txtContraseñaI.setToolTipText("Ingrese una contraseña que sea segura y que pueda recordar fácilmente.");
                txtContraseñaI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                btnAceptarI.setBackground(new java.awt.Color(255, 0, 0));
                btnAceptarI.setForeground(new java.awt.Color(255, 255, 255));
                btnAceptarI.setText("Aceptar");
                btnAceptarI.setBorder(new javax.swing.border.MatteBorder(null));
                btnAceptarI.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarIActionPerformed(evt);
                        }
                });

                btnCancelar1.setBackground(new java.awt.Color(0, 0, 0));
                btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
                btnCancelar1.setText("Cancelar");
                btnCancelar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                new java.awt.Color(255, 255, 255)));
                btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelar1ActionPerformed(evt);
                        }
                });

                btnAtras1.setText("Atrás");
                btnAtras1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAtras1ActionPerformed(evt);
                        }
                });

                jLabel6.setBackground(new java.awt.Color(0, 0, 0));
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Recuerde que si ya tiene una cuenta, debe dirigirse al botón 'Ingresar'.");
                jLabel6.setToolTipText("El botón 'Ingresar' se encuentra en el menú 'Registrarme como'.");

                javax.swing.GroupLayout lblCorreo1Layout = new javax.swing.GroupLayout(lblCorreo1);
                lblCorreo1.setLayout(lblCorreo1Layout);
                lblCorreo1Layout.setHorizontalGroup(
                                lblCorreo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lblCorreo1Layout.createSequentialGroup()
                                                                .addGroup(lblCorreo1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(lblCorreo1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(lblRegistrarme1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                207,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(lblCorreo1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(24, 24, 24)
                                                                                                .addGroup(lblCorreo1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(lblCorreo1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtCorreoI))
                                                                                                                .addGroup(lblCorreo1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblNombre1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtNombreI))
                                                                                                                .addGroup(lblCorreo1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblContraseña1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtContraseñaI))
                                                                                                                .addComponent(jLabel6,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                371,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addGap(20, 20, 20))
                                                .addGroup(lblCorreo1Layout.createSequentialGroup()
                                                                .addGap(71, 71, 71)
                                                                .addComponent(btnAceptarI,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnCancelar1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(79, 79, 79))
                                                .addGroup(lblCorreo1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btnAtras1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                lblCorreo1Layout.setVerticalGroup(
                                lblCorreo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lblCorreo1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblRegistrarme1)
                                                                .addGap(33, 33, 33)
                                                                .addGroup(lblCorreo1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblNombre1)
                                                                                .addComponent(txtNombreI,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(lblCorreo1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(txtCorreoI,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(lblCorreo1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtContraseñaI,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblContraseña1))
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                57, Short.MAX_VALUE)
                                                                .addGroup(lblCorreo1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnAceptarI,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                41,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnCancelar1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                41,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(btnAtras1)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(219, 219, 219)
                                                                .addComponent(lblCorreo1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(539, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(516, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(lblCorreo1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>

        private void btnAceptarIActionPerformed(java.awt.event.ActionEvent evt) {
                try {

                        if (txtNombreI.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su primer nombre para completar el registro.");
                                return;
                        }

                        if (txtCorreoI.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su correo electrónico para completar el registro.");
                                return;
                        }

                        if (txtContraseñaI.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que cree una contraseña para completar el registro.");
                                return;
                        }

                        int id = generarNuevoId();

                        String nombre = txtNombreI.getText();
                        String correo = txtCorreoI.getText();
                        String contraseña = txtContraseñaI.getText();
                        String tipo = "Invitado";
                        String ubicacion = "";
                        String cedula = "";

                        Usuario oUsuario = new Usuario(id, nombre, cedula, correo, contraseña, tipo, ubicacion);
                        PersistenciaUsuarioTabla.setUsuario(oUsuario);

                        String contraseñaHash = oUsuario.getContraseña();
                        // Guardar en la base de Datos
                        try (Connection conn = DatabaseConnection.getConnection()) {
                                String sql = "INSERT INTO Usuarios (nombre, correo, contraseña, tipo) VALUES (?, ?, ?, ?)";
                                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                                        pstmt.setString(1, nombre);
                                        pstmt.setString(2, correo);
                                        pstmt.setString(3, contraseñaHash);
                                        pstmt.setString(4, tipo);
                                        pstmt.executeUpdate();
                                }

                        }

                        JOptionPane.showMessageDialog(this, "Bienvenido!!");

                        FrmEmpresa oFrmEmpresa = new FrmEmpresa();

                        oFrmEmpresa.setExtendedState(JFrame.MAXIMIZED_BOTH);

                        oFrmEmpresa.setVisible(true);

                        this.dispose();

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage());
                }
        }

        private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {

                int respuesta = JOptionPane.showConfirmDialog(this, "Desea borrar la informacón escrita?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        txtNombreI.setText("");
                        txtCorreoI.setText("");
                        txtContraseñaI.setText("");
                }
        }

        private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {
                formWindowClosing(new WindowEvent(this, 0));
        }

        private void formWindowClosing(java.awt.event.WindowEvent evt) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Desea abandonar el área de Registrarse?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        this.dispose();
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarInvitado.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarInvitado.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarInvitado.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarInvitado.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {

                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btnAceptarI;
        private javax.swing.JButton btnAtras1;
        private javax.swing.JButton btnCancelar1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblContraseña1;
        private javax.swing.JPanel lblCorreo1;
        private javax.swing.JLabel lblNombre1;
        private javax.swing.JLabel lblRegistrarme1;
        private javax.swing.JTextField txtContraseñaI;
        private javax.swing.JTextField txtCorreoI;
        private javax.swing.JTextField txtNombreI;
        // End of variables declaration
}

class FondoInvitado extends JPanel {
        private ImageIcon registrarInvitadp;

        public FondoInvitado() {

                registrarInvitadp = new ImageIcon(
                                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-FPFa9rohFBrgB3api3M5HG.jpg");
                if (registrarInvitadp.getImageLoadStatus() != MediaTracker.COMPLETE) {
                        System.err.println("Error al cargar la imagen de fondo.");
                }
        }

        @Override
        protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (registrarInvitadp != null) {
                        g.drawImage(registrarInvitadp.getImage(), 0, 0, getWidth(), getHeight(), this);
                }
        }

}
