package entidades.appMonjarrez;

import static entidades.PersistenciaUsuario.PersistenciaUsuarioTabla.generarNuevoId;

import entidades.Usuario;
import entidades.VRegistro;
import entidades.PersistenciaUsuario.PersistenciaUsuarioTabla;

import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmRegistrarVendedor extends javax.swing.JFrame {
        FondoRegistrar fondo = new FondoRegistrar();
        Usuario oUsuario;
        TipoMantenimiento oTipo;
        VRegistro vRegistro = new VRegistro();

        /**
         * Creates new form FrmRegistrarUsuario
         */
        public FrmRegistrarVendedor(TipoMantenimiento tipo, Usuario oUsuario) {
                setContentPane(fondo);
                initComponents();
                this.oTipo = tipo;
                this.oUsuario = oUsuario;

                switch (tipo) {
                        case AGREGAR:
                                // Configuración para agregar
                                txtNombre.setEnabled(true);
                                txtCorreo.setEnabled(true);
                                txtContraseña.setEnabled(true);
                                break;
                        case MODIFICAR:
                                // Configuración para modificar
                                txtNombre.setText(oUsuario.getNombre());
                                txtCorreo.setText(oUsuario.getCorreo());
                                txtContraseña.setText(oUsuario.getContraseña());
                                txtNombre.setEnabled(true);
                                txtCorreo.setEnabled(true);
                                txtContraseña.setEnabled(true);
                                break;
                        default:
                                break;

                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
      //  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facebook-verificado.png"))); // NOI18N
        jLabel1.setText("Monjarrez");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCorreo.setBackground(new java.awt.Color(0, 0, 0));

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setToolTipText("\"Señor usuario, por favor ingrese su primer nombre para registrarse.");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");

        txtCorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setToolTipText("Por favor, ingrese su correo electrónico personal o el que usa con más frecuencia.");
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lblContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña");

        txtContraseña.setBackground(new java.awt.Color(0, 0, 0));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setToolTipText("Ingrese una contraseña que sea segura y que pueda recordar fácilmente.");
        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnAceptar.setBackground(new java.awt.Color(255, 0, 0));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recuerde que si ya tiene una cuenta, debe dirigirse al botón 'Ingresar'.");
        jLabel3.setToolTipText("El botón 'Ingresar' se encuentra en el menú 'Registrarme como'.");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrarme");

        javax.swing.GroupLayout lblCorreoLayout = new javax.swing.GroupLayout(lblCorreo);
        lblCorreo.setLayout(lblCorreoLayout);
        lblCorreoLayout.setHorizontalGroup(
            lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña)
                .addGap(32, 32, 32))
            .addGroup(lblCorreoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCorreoLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(lblCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lblCorreoLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtNombre)))
                .addGap(41, 41, 41))
            .addGroup(lblCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo)
                .addGap(32, 32, 32))
        );
        lblCorreoLayout.setVerticalGroup(
            lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblCorreoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(97, 97, 97)
                .addGroup(lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>             

        private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {
                formWindowClosing(new WindowEvent(this, 0));

        }

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Desea borrar la informacón escrita?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        txtNombre.setText("");
                        txtCorreo.setText("");
                        txtContraseña.setText("");
                }

        }

        private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {
                try {

                        // Validaciones
                        if (txtNombre.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su primer nombre para completar el registro.");
                                return;
                        }

                        if (txtCorreo.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su correo electrónico para completar el registro.");
                                return;
                        }

                        if (txtContraseña.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que cree una contraseña para completar el registro.");
                                return;
                        }

                       

                        int id = generarNuevoId();
                        String nombre = txtNombre.getText();
                        String cedula = "";
                        String correo = txtCorreo.getText();
                        String contraseña = txtContraseña.getText();
                        String tipo = "Vendedor";
                        String ubicacion = "";

                        Usuario oUsuario = new Usuario(id, nombre, cedula, correo, contraseña, tipo,
                                        ubicacion);
                        PersistenciaUsuarioTabla.setUsuario(oUsuario);

                        String contraseñaHash = oUsuario.getContraseña();
                        // Guardar en la base de datos
                        // Registrar al usuario
                        vRegistro.registrarUsuario(nombre, correo, contraseñaHash, tipo);

                        String mensaje = "Estimado usuario,\n\n"
                                        + "\nPara poder registrarse como vendedor, es necesario que se suscriba. "
                                        + "\nSin embargo, antes de pagar la suscripción, debe enviar una solicitud de vendedor. "
                                        + "\nEsto es para obtener los permisos necesarios para vender y ser verificado por la aplicación Monjarrez.\n\n"
                                        + "\nSolo serán unos pequeños datos que deberá ingresar.";

                        JOptionPane.showMessageDialog(null, mensaje);

                        FrmTablaUsuario oFrmTablaUsuario = new FrmTablaUsuario();
                        oFrmTablaUsuario.setVisible(true);

                        FrmSolicitudDeVendedor oFrmSolicitudDeVendedor = new FrmSolicitudDeVendedor(oFrmTablaUsuario);

                        String solicitudTexto = "Nombre: " + nombre + "\nCorreo: " + correo + "\nTipo: " + tipo;
                        oFrmSolicitudDeVendedor.getTxtaSolicitudes().setText(solicitudTexto);

                        oFrmSolicitudDeVendedor.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        oFrmSolicitudDeVendedor.setVisible(true);

                        this.dispose();

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage());
                }

        }

       
        private void formWindowClosing(java.awt.event.WindowEvent evt) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Desea abandonar el área de Registrarse?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        this.dispose();
                }
        }

      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btnAceptar;
        private javax.swing.JButton btnAtras;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblContraseña;
        private javax.swing.JPanel lblCorreo;
        private javax.swing.JLabel lblNombre;
        private javax.swing.JTextField txtContraseña;
        private javax.swing.JTextField txtCorreo;
        private javax.swing.JTextField txtNombre;
        // End of variables declaration
}

class FondoRegistrar extends JPanel {
        private ImageIcon registrar;

        public FondoRegistrar() {

                registrar = new ImageIcon(
                                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-BaT5HppapmHa4WXvGDfMRK.jpg");
                if (registrar.getImageLoadStatus() != MediaTracker.COMPLETE) {
                        System.err.println("Error al cargar la imagen de fondo.");
                }
        }

        @Override
        protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (registrar != null) {
                        g.drawImage(registrar.getImage(), 0, 0, getWidth(), getHeight(), this);
                }
        }

}
