package entidades.appMonjarrez;

import entidades.DatabaseConnection;
import entidades.Usuario;
import entidades.PersistenciaUsuario.PersistenciaUsuarioTabla;
import static entidades.PersistenciaUsuario.PersistenciaUsuarioTabla.generarNuevoId;
import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmRegistrarComprador extends javax.swing.JFrame {
        FondoRegistrarVendedor fondo = new FondoRegistrarVendedor();
        Usuario oUsuario;
        TipoMantenimiento oTipo;

        /**
         * Creates new form FrmRegistrarVendedor
         */
        public FrmRegistrarComprador(TipoMantenimiento tipo, Usuario oUsuario) {
                setContentPane(fondo);
                initComponents();

                this.oTipo = tipo;
                this.oUsuario = oUsuario;

                switch (tipo) {
                        case AGREGAR:
                                // Configuración para agregar
                                txtNombreV.setEnabled(true);
                                txtCorreoV.setEnabled(true);
                                txtContraseñaV.setEnabled(true);
                                break;
                        case MODIFICAR:
                                // Configuración para modificar
                                txtNombreV.setText(oUsuario.getNombre());
                                txtCorreoV.setText(oUsuario.getCorreo());
                                txtContraseñaV.setText(oUsuario.getContraseña());
                                txtNombreV.setEnabled(true);
                                txtCorreoV.setEnabled(true);
                                txtContraseñaV.setEnabled(true);
                                break;
                        default:
                                break;
                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                lblCorreo = new javax.swing.JPanel();
                lblRegistrarme = new javax.swing.JLabel();
                lblNombre = new javax.swing.JLabel();
                txtNombreV = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtCorreoV = new javax.swing.JTextField();
                lblContraseña = new javax.swing.JLabel();
                txtContraseñaV = new javax.swing.JTextField();
                btnAceptarV = new javax.swing.JButton();
                btnCancelar = new javax.swing.JButton();
                btnAtras = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));
                jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                jLabel1.setBackground(new java.awt.Color(0, 0, 0));
                jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(204, 0, 0));
                // jLabel1.setIcon(new
                // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/facebook-verificado.png")));
                // // NOI18N
                jLabel1.setText("Monjarrez");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                296,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                61, Short.MAX_VALUE)
                                                                .addContainerGap()));

                lblCorreo.setBackground(new java.awt.Color(0, 0, 0));

                lblRegistrarme.setBackground(new java.awt.Color(255, 255, 255));
                lblRegistrarme.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                lblRegistrarme.setForeground(new java.awt.Color(255, 255, 255));
                lblRegistrarme.setText("Registrarme");

                lblNombre.setBackground(new java.awt.Color(0, 0, 0));
                lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                lblNombre.setForeground(new java.awt.Color(255, 255, 255));
                lblNombre.setText("Nombre");

                txtNombreV.setBackground(new java.awt.Color(0, 0, 0));
                txtNombreV.setForeground(new java.awt.Color(255, 255, 255));
                txtNombreV.setToolTipText("\"Señor usuario, por favor ingrese su primer nombre para registrarse.");
                txtNombreV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                jLabel4.setBackground(new java.awt.Color(0, 0, 0));
                jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Correo");

                txtCorreoV.setBackground(new java.awt.Color(0, 0, 0));
                txtCorreoV.setForeground(new java.awt.Color(255, 255, 255));
                txtCorreoV.setToolTipText(
                                "Por favor, ingrese su correo electrónico personal o el que usa con más frecuencia.");
                txtCorreoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                lblContraseña.setBackground(new java.awt.Color(0, 0, 0));
                lblContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
                lblContraseña.setText("Contraseña");

                txtContraseñaV.setBackground(new java.awt.Color(0, 0, 0));
                txtContraseñaV.setForeground(new java.awt.Color(255, 255, 255));
                txtContraseñaV.setToolTipText("Ingrese una contraseña que sea segura y que pueda recordar fácilmente.");
                txtContraseñaV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                btnAceptarV.setBackground(new java.awt.Color(255, 0, 0));
                btnAceptarV.setForeground(new java.awt.Color(255, 255, 255));
                btnAceptarV.setText("Aceptar");
                btnAceptarV.setBorder(new javax.swing.border.MatteBorder(null));
                btnAceptarV.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarVActionPerformed(evt);
                        }
                });

                btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
                btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
                btnCancelar.setText("Cancelar");
                btnCancelar
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                btnAtras.setText("Atrás");
                btnAtras.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAtrasActionPerformed(evt);
                        }
                });

                jLabel3.setBackground(new java.awt.Color(0, 0, 0));
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Recuerde que si ya tiene una cuenta, debe dirigirse al botón 'Ingresar'.");
                jLabel3.setToolTipText("El botón 'Ingresar' se encuentra en el menú 'Registrarme como'.");

                javax.swing.GroupLayout lblCorreoLayout = new javax.swing.GroupLayout(lblCorreo);
                lblCorreo.setLayout(lblCorreoLayout);
                lblCorreoLayout.setHorizontalGroup(
                                lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lblCorreoLayout.createSequentialGroup()
                                                                .addGroup(lblCorreoLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(lblCorreoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(lblRegistrarme,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                207,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(lblCorreoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(24, 24, 24)
                                                                                                .addGroup(lblCorreoLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(lblCorreoLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtCorreoV))
                                                                                                                .addGroup(lblCorreoLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblNombre,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtNombreV))
                                                                                                                .addGroup(lblCorreoLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblContraseña,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtContraseñaV))
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                371,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addGap(20, 20, 20))
                                                .addGroup(lblCorreoLayout.createSequentialGroup()
                                                                .addGap(71, 71, 71)
                                                                .addComponent(btnAceptarV,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnCancelar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(79, 79, 79))
                                                .addGroup(lblCorreoLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btnAtras,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                73,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                lblCorreoLayout.setVerticalGroup(
                                lblCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lblCorreoLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblRegistrarme)
                                                                .addGap(33, 33, 33)
                                                                .addGroup(
                                                                                lblCorreoLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(lblNombre)
                                                                                                .addComponent(txtNombreV,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(lblCorreoLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(txtCorreoV,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(
                                                                                lblCorreoLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(txtContraseñaV,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(lblContraseña))
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                57,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(
                                                                                lblCorreoLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(btnAceptarV,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                41,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(btnCancelar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                41,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(26, 26, 26)
                                                                .addComponent(btnAtras)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(538, Short.MAX_VALUE)
                                                                .addComponent(lblCorreo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(536, 536, 536)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                32,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblCorreo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>

        private void btnAceptarVActionPerformed(java.awt.event.ActionEvent evt) {
                try {

                        if (txtNombreV.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su primer nombre para completar el registro.");
                                return;
                        }
                        //
                        if (txtCorreoV.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su correo electrónico para completar el registro.");
                                return;
                        }

                        if (txtContraseñaV.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que cree una contraseña para completar el registro.");
                                return;
                        }

                        int id = generarNuevoId();

                        String nombre = txtNombreV.getText();
                        String cedula = "";
                        String correo = txtCorreoV.getText();
                        String contraseña = txtContraseñaV.getText();
                        String tipo = "Comprador";
                        String ubicacion = "";

                        Usuario oUsuario = new Usuario(id, nombre, cedula, correo, contraseña, tipo,
                                        ubicacion);
                        PersistenciaUsuarioTabla.setUsuario(oUsuario);

                        String contraseñaHash = oUsuario.getContraseña();
                        // Guardar en la base de Datos
                        try (Connection conn = DatabaseConnection.getConnection()) {
                                String sql = "INSERT INTO Usuarios (nombre, correo, contraseña, tipo) VALUES (?, ?, ?, ?)";
                                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                                        pstmt.setString(1, nombre);
                                        pstmt.setString(2, correo);
                                        pstmt.setString(3, contraseñaHash);
                                        pstmt.setString(4, tipo);
                                        pstmt.executeUpdate();
                                }

                        }

                        JOptionPane.showMessageDialog(this, "Bienvenido!!");

                        FrmEmpresa oFrmEmpresa = new FrmEmpresa();

                        oFrmEmpresa.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la Ventana,
                                                                             // al tamaño de la pantalla

                        oFrmEmpresa.setVisible(true);

                        this.dispose();

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage());
                }

        }

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Desea borrar la informacón escrita?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        txtNombreV.setText("");
                        txtCorreoV.setText("");
                        txtContraseñaV.setText("");
                }

        }

        private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {
                formWindowClosing(new WindowEvent(this, 0));

        }

        private void formWindowClosing(java.awt.event.WindowEvent evt) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Desea abandonar el área de Registrarse?",
                                "Atención", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                        this.dispose();
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmRegistrarVendedor.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {

                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btnAceptarV;
        private javax.swing.JButton btnAtras;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblContraseña;
        private javax.swing.JPanel lblCorreo;
        private javax.swing.JLabel lblNombre;
        private javax.swing.JLabel lblRegistrarme;
        private javax.swing.JTextField txtContraseñaV;
        private javax.swing.JTextField txtCorreoV;
        private javax.swing.JTextField txtNombreV;
        // End of variables declaration
}

class FondoRegistrarVendedor extends JPanel {
        private ImageIcon registrarVendedor;

        public FondoRegistrarVendedor() {

                registrarVendedor = new ImageIcon(
                                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-PTExQfUtcLuaZKYQ5oUu7m.jpg");
                if (registrarVendedor.getImageLoadStatus() != MediaTracker.COMPLETE) {
                        System.err.println("Error al cargar la imagen de fondo.");
                }
        }

        @Override
        protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (registrarVendedor != null) {
                        g.drawImage(registrarVendedor.getImage(), 0, 0, getWidth(), getHeight(), this);
                }
        }

}
