package entidades.appMonjarrez;

import entidades.PersistenciaUsuario.PersistenciaSolicitudUsuario;
import entidades.DatabaseConnection;
import entidades.SolicitudesDeVendedor;
import entidades.Usuario;

import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmSolicitudDeVendedor extends javax.swing.JFrame {
        Usuario oUsuario;
        // private FrmTablaUsuario oFrmTablaUsuario;

        FondoRegistrar fondo = new FondoRegistrar();
        private JTextArea txtaSolicitudes;

        /**
         * Creates new form FrmSolicitudDeVendedor
         */
        public FrmSolicitudDeVendedor(FrmTablaUsuario oFrmTablaUsuario) {
                // this.oFrmTablaUsuario = oFrmTablaUsuario;
                setContentPane(fondo);

                initComponents();

                // this.oUsuario = oUsuario;

                txtaSolicitudes = new JTextArea();
                txtaSolicitudes.setColumns(20);
                txtaSolicitudes.setRows(5);

                JScrollPane scrollPane = new JScrollPane(txtaSolicitudes);
                this.add(scrollPane);
                bntEnviarSolicitud.setEnabled(true);

                btnSuscribirse.setEnabled(false);
        }

        // private void someActionToOpenSolicitudDeVendedor() {
        // if (oFrmTablaUsuario != null) {
        // FrmSolicitudDeVendedor frmSolicitudDeVendedor = new
        // FrmSolicitudDeVendedor(oFrmTablaUsuario);
        // frmSolicitudDeVendedor.setVisible(true);
        // } else {
        // JOptionPane.showMessageDialog(this, "Error: La referencia a FrmTablaUsuario
        // es nula.");
        // }
        // }

        public JTextArea getTxtaSolicitudes() {
                return txtaSolicitudes;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblMonjarrez1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                txtNombreProducto = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtPrecioPromedio = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtCorreoDelVendedor = new javax.swing.JTextField();
                bntEnviarSolicitud = new javax.swing.JButton();
                btnAtras = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                txtProvincia = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtCanton = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                txtDescripcion = new javax.swing.JTextField();
                btnSuscribirse = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Solicitud de Vendedor ");

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));
                jPanel1.setForeground(new java.awt.Color(204, 0, 0));

                lblMonjarrez1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                lblMonjarrez1.setForeground(new java.awt.Color(204, 0, 0));
                // lblMonjarrez1.setIcon(new
                // javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/facebook-verificado.png")));
                // // NOI18N
                lblMonjarrez1.setText("Monjarrez");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblMonjarrez1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                271,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(15, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblMonjarrez1)
                                                                .addContainerGap()));

                jPanel2.setBackground(new java.awt.Color(0, 0, 0));
                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maestro",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
                jPanel2.setToolTipText("");

                jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Nombre del Producto");

                txtNombreProducto.setBackground(new java.awt.Color(0, 0, 0));
                txtNombreProducto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
                txtNombreProducto
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Precio Promedio");

                txtPrecioPromedio.setBackground(new java.awt.Color(0, 0, 0));
                txtPrecioPromedio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtPrecioPromedio.setForeground(new java.awt.Color(255, 255, 255));
                txtPrecioPromedio
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));

                jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Correo del Vendedor");

                txtCorreoDelVendedor.setBackground(new java.awt.Color(0, 0, 0));
                txtCorreoDelVendedor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtCorreoDelVendedor.setForeground(new java.awt.Color(255, 255, 255));
                txtCorreoDelVendedor
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));

                bntEnviarSolicitud.setBackground(new java.awt.Color(204, 0, 0));
                bntEnviarSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                bntEnviarSolicitud.setForeground(new java.awt.Color(0, 0, 0));
                bntEnviarSolicitud.setText("Enviar solicitud");
                bntEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bntEnviarSolicitudActionPerformed(evt);
                        }
                });

                btnAtras.setBackground(new java.awt.Color(204, 204, 204));
                btnAtras.setForeground(new java.awt.Color(0, 0, 0));
                btnAtras.setText("Atrás");
                btnAtras.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAtrasActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Provincia");

                txtProvincia.setBackground(new java.awt.Color(0, 0, 0));
                txtProvincia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtProvincia.setForeground(new java.awt.Color(255, 255, 255));
                txtProvincia
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));

                jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Cantón");

                txtCanton.setBackground(new java.awt.Color(0, 0, 0));
                txtCanton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtCanton.setForeground(new java.awt.Color(255, 255, 255));
                txtCanton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                new java.awt.Color(255, 255, 255)));

                jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Ingrese los Datos");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(btnAtras,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                73,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(bntEnviarSolicitud)
                                                                                                                .addGap(18, 18, 18))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                118,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                146,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabel6,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                64,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                93,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGap(33, 33, 33)
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(txtProvincia,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                240,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtCanton,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                240,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtNombreProducto,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                240,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtPrecioPromedio,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                240,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtCorreoDelVendedor,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                240,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                212,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 204, Short.MAX_VALUE)))));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(txtProvincia,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                29,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(txtCanton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(txtNombreProducto,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(37, 37, 37)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(txtPrecioPromedio,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(47, 47, 47)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(txtCorreoDelVendedor,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(49, 49, 49)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(bntEnviarSolicitud,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                39,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnAtras))
                                                                .addContainerGap()));

                jPanel3.setBackground(new java.awt.Color(0, 0, 0));
                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción del Produccto",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
                jPanel3.setForeground(new java.awt.Color(255, 255, 255));

                txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
                txtDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
                txtDescripcion.setText("Escribe aqui...");
                txtDescripcion
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                                                new java.awt.Color(255, 255, 255)));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 635,
                                                                Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(txtDescripcion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                202,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                btnSuscribirse.setBackground(new java.awt.Color(102, 102, 0));
                btnSuscribirse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                btnSuscribirse.setForeground(new java.awt.Color(0, 0, 0));
                btnSuscribirse.setText("Suscribirse");
                btnSuscribirse.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSuscribirseActionPerformed(evt);
                        }
                });

                jButton2.setBackground(new java.awt.Color(204, 204, 204));
                jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jButton2.setForeground(new java.awt.Color(0, 0, 0));
                jButton2.setText("Atrás");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jPanel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                73,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(211, 211, 211)
                                                                                                .addComponent(jPanel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                601,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnSuscribirse,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                122,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jPanel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(btnSuscribirse,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                41,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                731,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton2)
                                                                                                .addGap(19, 19, 19))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(jPanel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jPanel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(66, 66, 66)))));

                pack();
        }// </editor-fold>

        private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();
        }

        private void bntEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {
                try {

                        if (txtProvincia.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese el nombre de la Provincia donde se ubica su producto.");
                                return;
                        }
                        if (txtCanton.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese el nombre del cantón donde se ubica su producto.");
                                return;
                        }
                        if (txtNombreProducto.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese el nombre del producto.");
                                return;
                        }
                        if (txtDescripcion.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese la descripción del producto.");
                                return;
                        }
                        if (txtPrecioPromedio.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese el promedio de precio de su producto.");
                                return;
                        }
                        if (txtCorreoDelVendedor.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null,
                                                "Estimado usuario, es necesario que ingrese su correo de Usuario.");
                                return;
                        }

                        int id = PersistenciaSolicitudUsuario.generarNuevoId();
                        String provincia = txtProvincia.getText();
                        String canton = txtCanton.getText();
                        String nombre = txtNombreProducto.getText();
                        String descripcion = txtDescripcion.getText();
                        double precioPromedio = Double.parseDouble(txtPrecioPromedio.getText());
                        String correo = txtCorreoDelVendedor.getText();

                        // Guardar en la base de datos
                        try (Connection conn = DatabaseConnection.getConnection()) {
                                String sql = "INSERT INTO SolicitudesDeVendedor (provincia, canton, nombre_producto, descripcion, precio_promedio, correo_vendedor) VALUES (?, ?, ?, ?, ?, ?)";
                                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                                        pstmt.setString(1, provincia);
                                        pstmt.setString(2, canton);
                                        pstmt.setString(3, nombre);
                                        pstmt.setString(4, descripcion);
                                        pstmt.setDouble(5, precioPromedio);
                                        pstmt.setString(6, correo);
                                        pstmt.executeUpdate();
                                }
                        }

                         SolicitudesDeVendedor nuevaSolicitud = new SolicitudesDeVendedor(id,
                         provincia, canton, nombre,
                         descripcion,
                         precioPromedio, correo);

                         PersistenciaSolicitudUsuario.agregarSolicitud(nuevaSolicitud);

                        String mensaje = "La solicitud fue enviada con éxito:\n" +
                                        "ID: " + id + "\n" +
                                        "Provincia: " + provincia + "\n" +
                                        "Cantón: " + canton + "\n" +
                                        "Nombre del Producto: " + nombre + "\n" +
                                        "Descripción: " + descripcion + "\n" +
                                        "Precio Promedio: " + precioPromedio + "\n" +
                                        "Correo del Vendedor: " + correo + "\n" +
                                        "Un administrador de empresa Monjarrez se contactará con usted por medio de su correo.";

                        JOptionPane.showMessageDialog(null, mensaje);

                        JOptionPane.showMessageDialog(null,
                                        "La solicitud fue enviada, un administrador de empresa Monjarrez se contactará con usted por medio de su correo"
                                                        + "\n" +
                                                        "Por el momento puedes ir viendo las opciones de Suscripción que te Ofrecemos");
                        btnSuscribirse.setEnabled(true);

                        bntEnviarSolicitud.setEnabled(false);

                        // Enviar a suscribirse
                        FrmSuscribirme oFrmSuscribirme = new FrmSuscribirme();

                        oFrmSuscribirme.setVisible(true);

                        oFrmSuscribirme.setLocationRelativeTo(null);

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage());
                }

        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();
        }

        private void btnSuscribirseActionPerformed(java.awt.event.ActionEvent evt) {

                JOptionPane.showMessageDialog(null, "Bienvenido Emprendedor !!");

                FrmEmpresa oFrmEmpresa = new FrmEmpresa();

                oFrmEmpresa.setExtendedState(JFrame.MAXIMIZED_BOTH);

                oFrmEmpresa.setVisible(true);

                this.dispose();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FrmSolicitudDeVendedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FrmSolicitudDeVendedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FrmSolicitudDeVendedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FrmSolicitudDeVendedor.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {

                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton bntEnviarSolicitud;
        private javax.swing.JButton btnAtras;
        private javax.swing.JButton btnSuscribirse;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JLabel lblMonjarrez1;
        private javax.swing.JTextField txtCanton;
        private javax.swing.JTextField txtCorreoDelVendedor;
        private javax.swing.JTextField txtDescripcion;
        private javax.swing.JTextField txtNombreProducto;
        private javax.swing.JTextField txtPrecioPromedio;
        private javax.swing.JTextField txtProvincia;
        // End of variables declaration
}
