package entidades.appMonjarrez;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import entidades.DatabaseConnection;
import entidades.Suscripcion;
import entidades.VRegistro;

public class FrmSuscribirme extends javax.swing.JFrame {
    FondoSesion fondo = new FondoSesion();
    VRegistro vRegistro = new VRegistro();
    private int intentos = 0;

    /**
     * Creates new form FrmSuscribirme
     */
    public FrmSuscribirme() {
        setContentPane(fondo);
        initComponents();
    }

    /**
     * Método para validar el número de tarjeta
     */
    private boolean validarNumeroTarjeta(String numeroTarjeta) {
        if (numeroTarjeta == null || !numeroTarjeta.matches("\\d+")) {
            return false;
        }

        int longitud = numeroTarjeta.length();
        String primerDigito = numeroTarjeta.substring(0, 1);
        String rangoMasterCard = numeroTarjeta.substring(0, 2);

        if (longitud == 16 && (primerDigito.equals("4")
                || (Integer.parseInt(rangoMasterCard) >= 51 && Integer.parseInt(rangoMasterCard) <= 55))) {
            return true;
        } else if (longitud == 15 && (primerDigito.equals("3"))) {
            return true;
        } else if (longitud == 16 && primerDigito.equals("6")) {
            return true;
        }
        return false;
    }

    /**
     * Método para validar el código de seguridad
     */
    private boolean validarCodigoSeguridad(String numeroTarjeta, String codigoSeguridad) {
        if (codigoSeguridad == null || !codigoSeguridad.matches("\\d+")) {
            return false;
        }

        int longitud = codigoSeguridad.length();
        if (numeroTarjeta.length() == 16) {
            return longitud == 3;
        } else if (numeroTarjeta.length() == 15) {
            return longitud == 4;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSuscribirme = new javax.swing.JButton();
        txtaSuscripcionNormal = new java.awt.TextArea();
        txtaSuscripcionAvanzada = new java.awt.TextArea();
        rbNormal = new javax.swing.JRadioButton();
        rbAvanzada = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblMonjarrez = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUbicación = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSuscribirme.setBackground(new java.awt.Color(204, 0, 0));
        btnSuscribirme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuscribirme.setForeground(new java.awt.Color(0, 0, 0));
       // btnSuscribirme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facebook-verificado.png"))); // NOI18N
        btnSuscribirme.setText("Suscribirme");
        btnSuscribirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuscribirmeActionPerformed(evt);
            }
        });

        txtaSuscripcionNormal.setBackground(new java.awt.Color(0, 0, 0));
        txtaSuscripcionNormal.setForeground(new java.awt.Color(255, 255, 255));
        txtaSuscripcionNormal.setText(
                "Ventajas para el usuario : \n 1.Acceso a contenido básico.\n2.Soporte técnico limitado.\n3.Descuento 10% pago en efectivo \nen Sucursal.\n\n\n\n\n\n\n\n\n\n\n\nPRECIO_BASICA = 15000.0");

        txtaSuscripcionAvanzada.setBackground(new java.awt.Color(0, 0, 0));
        txtaSuscripcionAvanzada.setForeground(new java.awt.Color(255, 255, 255));
        txtaSuscripcionAvanzada.setText(
                "Ventajas para el usuario :\n1.Acceso a todo el contenido.\n2.Soporte técnico prioritario.\n2.Acceso a promociones exclusivas\n\n\n\n\n\n\n\n\n\n\n\n\nPRECIO_AVANZADA = 30000.0\n");

        buttonGroup1.add(rbNormal);
        rbNormal.setForeground(new java.awt.Color(255, 255, 255));
        rbNormal.setText("Basica");

        buttonGroup1.add(rbAvanzada);
        rbAvanzada.setForeground(new java.awt.Color(255, 255, 255));
        rbAvanzada.setText("Avanzada");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        lblMonjarrez.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblMonjarrez.setForeground(new java.awt.Color(204, 0, 0));
       // lblMonjarrez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facebook-verificado.png"))); // NOI18N
        lblMonjarrez.setText("Monjarrez");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMonjarrez, javax.swing.GroupLayout.PREFERRED_SIZE, 237,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMonjarrez)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Cedula :");

        txtCedula.setBackground(new java.awt.Color(0, 0, 0));
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*Ubicación de Emprendimiento :");

        txtUbicación.setBackground(new java.awt.Color(0, 0, 0));
        txtUbicación.setForeground(new java.awt.Color(255, 255, 255));
        txtUbicación
                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Correo :");

        txtCorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Contraseña :");

        txtContraseña.setBackground(new java.awt.Color(0, 0, 0));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña
                .setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(txtaSuscripcionNormal,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 266,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(txtaSuscripcionAvanzada,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 266,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(96, 96, 96)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtUbicación))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        103,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtContraseña))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        69,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtCedula,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        259,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        69,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(txtCorreo,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        258,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 122, Short.MAX_VALUE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(104, 104, 104)
                                                                .addComponent(rbNormal,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(164, 164, 164)
                                                .addComponent(rbAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSuscribirme)))
                                .addGap(23, 23, 23)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbNormal)
                                                        .addComponent(rbAvanzada))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(btnSuscribirme)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtaSuscripcionNormal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtaSuscripcionAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtUbicación,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtContraseña,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 29,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)));

        pack();
    }// </editor-fold>

    /**
     * @param evt
     */
    private void btnSuscribirmeActionPerformed(java.awt.event.ActionEvent evt) {
    // Verificar si se ha seleccionado un tipo de suscripción
    if (!rbNormal.isSelected() && !rbAvanzada.isSelected()) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un tipo de suscripción (Básica o Avanzada).");
        return;
    }

    // Determinar el tipo de suscripción
    String tipoSuscripcion = rbNormal.isSelected() ? "Básica" : "Avanzada";
    Suscripcion suscripcion = new Suscripcion(tipoSuscripcion);

    JOptionPane.showMessageDialog(this, "Tipo de suscripción: " + suscripcion.getTipo() +
            "\nCosto: " + suscripcion.getCosto() +
            "\nBeneficios: " + suscripcion.getBeneficios());

    // Solicitar método de pago
    String metodoPagoStr = JOptionPane.showInputDialog(this, "¿Cómo desea pagar? (efectivo/tarjeta):");
    ETipoPago metodoPago;

    if (metodoPagoStr == null
            || (!metodoPagoStr.equalsIgnoreCase("efectivo") && !metodoPagoStr.equalsIgnoreCase("tarjeta"))) {
        JOptionPane.showMessageDialog(this, "Método de pago inválido.");
        return;
    } else if (metodoPagoStr.equalsIgnoreCase("efectivo")) {
        metodoPago = ETipoPago.EFECTIVO;
    } else {
        metodoPago = ETipoPago.TARJETA;

        String numeroTarjeta = JOptionPane.showInputDialog(this, "Ingrese el número de tarjeta (Sin espacios):");
        if (!validarNumeroTarjeta(numeroTarjeta)) {
            JOptionPane.showMessageDialog(this, "Número de tarjeta inválido.");
            return;
        }

        String codigoSeguridad = JOptionPane.showInputDialog(this, "Ingrese el código de seguridad:");
        if (!validarCodigoSeguridad(numeroTarjeta, codigoSeguridad)) {
            JOptionPane.showMessageDialog(this, "Código de seguridad inválido.");
            return;
        }

        String montoTarjetaStr = JOptionPane.showInputDialog(this, "Ingrese el monto a pagar con tarjeta:");
        if (montoTarjetaStr == null || !montoTarjetaStr.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
            return;
        }

        double montoTarjeta = Double.parseDouble(montoTarjetaStr);
        if (montoTarjeta < suscripcion.getCosto()) {
            JOptionPane.showMessageDialog(this, "El monto ingresado es menor que el precio a pagar.");
            return;
        }
    }

    // Procesar el pago en efectivo
    if (metodoPago == ETipoPago.EFECTIVO) {
        double descuento = suscripcion.getCosto() * 0.10;
        double montoConDescuento = suscripcion.getCosto() - descuento;

        String montoEfectivoStr = JOptionPane.showInputDialog(this, "Ingrese el monto con el que cancela:");
        if (montoEfectivoStr == null || !montoEfectivoStr.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
            return;
        }

        double montoEfectivo = Double.parseDouble(montoEfectivoStr);
        if (montoEfectivo < montoConDescuento) {
            JOptionPane.showMessageDialog(this, "El monto ingresado es menor que el total a pagar con descuento.");
            return;
        }

        double vuelto = montoEfectivo - montoConDescuento;
        JOptionPane.showMessageDialog(this, "El vuelto a entregar es: " + vuelto);
    }

// Validar correo y contraseña
try {
    if (txtCorreo.getText().isEmpty() || txtContraseña.getPassword().length == 0) {
        JOptionPane.showMessageDialog(this,
                "Estimado Usuario. Debe digitar sus datos de Inicio para acceder a su cuenta");
        return;
    }

    String correo = txtCorreo.getText();
    String contraseña = new String(txtContraseña.getPassword()); // Convertir char[] a String
    String hashedPassword = hashContraseña(contraseña); // Hashear la contraseña ingresada
    String cedula = txtCedula.getText();
    String ubicacion = txtUbicación.getText();

    // Conectar a la base de datos
    try (Connection conn = DatabaseConnection.getConnection()) {
        String sql = "SELECT * FROM Usuarios WHERE correo = ? AND contraseña = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, correo);
            pstmt.setString(2, hashedPassword); // Comparar el hash

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Inicio de sesión exitosa");
                    JOptionPane.showMessageDialog(this, "Bienvenido!!");

                    // Registrar al vendedor usando el correo
                    vRegistro.registrarVendedor(cedula, ubicacion, 1, tipoSuscripcion, correo);
                    JOptionPane.showMessageDialog(null, "Bienvenido Emprendedor !!");

                    FrmEmpresa oFrmEmpresa = new FrmEmpresa();
                    oFrmEmpresa.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    oFrmEmpresa.setVisible(true);

                    intentos = 0;
                    this.dispose();
                } else {
                    // Si no se encuentra el usuario
                    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Intente nuevamente.");
                    txtCorreo.setText("");
                    txtContraseña.setText("");

                    intentos++;
                    if (intentos >= 3) {
                        JOptionPane.showMessageDialog(null,
                                "Lo sentimos, se han agotado los intentos. El programa se cerrará.");
                        this.dispose();
                    }
                }
            }
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Ocurrió un error durante el inicio de sesión: " + e.getMessage());
    e.printStackTrace();
}



    this.dispose();
}



    // Método simulado para "hash" de la contraseña
    private String hashContraseña(String contraseña) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(contraseña.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1)
                    hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSuscribirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSuscribirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSuscribirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSuscribirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSuscribirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnSuscribirme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMonjarrez;
    private javax.swing.JRadioButton rbAvanzada;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtUbicación;
    private java.awt.TextArea txtaSuscripcionAvanzada;
    private java.awt.TextArea txtaSuscripcionNormal;
    // End of variables declaration
}
