package entidades.appMonjarrez;

import entidades.PersistenciaUsuario.PersistenciaSolicitudUsuario;
import entidades.PersistenciaUsuario.PersistenciaUsuarioTabla;
import entidades.SolicitudesDeVendedor;
import entidades.Usuario;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.MediaTracker;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JInternalFrame;

/**
 *
 * @author Iván Monjarrez
 */
public class FrmTablaUsuario extends JInternalFrame {

    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloSolicitudes;
    private static Usuario oUsuario;
    FondoTabla fondo = new FondoTabla();
   // private JTable tablaVendedores;

    public static Usuario getUsuario() {
        return oUsuario;
    }

    public static void setUsuario(Usuario oUsuario) {
        FrmTablaUsuario.oUsuario = oUsuario;
    }

    /**
     * Creates new form FrmTablaUsuario
     */
    public FrmTablaUsuario() {
        setContentPane(fondo);
        initComponents();

        setTitle("Tabla de Usuarios");
        setSize(800, 600);
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);

        tblUsuario.setPreferredSize(new Dimension(500, 300));
        tblSolicitudes.setPreferredSize(new Dimension(500, 300));

        modeloTabla = (DefaultTableModel) tblUsuario.getModel();

        modeloSolicitudes = (DefaultTableModel) tblSolicitudes.getModel();
        llenarTabla();
        llenarTablaSolicitudes();

        btnModificar.setEnabled(false);
        btnModificar2.setEnabled(false);
    }

    private void llenarTablaSolicitudes() {
        modeloSolicitudes.setRowCount(0);

        List<SolicitudesDeVendedor> solicitudes = PersistenciaSolicitudUsuario.obtenerSolicitudes();
        System.out.println("Número de solicitudes: " + solicitudes.size());

        for (SolicitudesDeVendedor solicitud : solicitudes) {
            Object[] fila = new Object[1];

            fila[0] = "ID: " + solicitud.getId() + ", Provincia: " + solicitud.getProvincia() +
                    ", Cantón: " + solicitud.getCanton() + ", Producto: " + solicitud.getNombreProducto() +
                    ", Descripción: " + solicitud.getDescripcion() +
                    ", Precio Promedio: " + solicitud.getPrecioPromedio() +
                    ", Correo: " + solicitud.getCorreoVendedor();
            modeloSolicitudes.addRow(fila);
        }

    }

    private void llenarTabla() {
        modeloTabla.setRowCount(0);
        List<Usuario> usuarios = PersistenciaUsuarioTabla.getListado();
        System.out.println("Número de usuarios: " + usuarios.size());
        for (Usuario usuario : usuarios) {
            Object[] fila = new Object[6];
            fila[0] = usuario.getId();
            fila[1] = usuario.getNombre();
            fila[2] = usuario.getCorreo();
            fila[3] = usuario.getContraseña();
            fila[4] = usuario.getTipo();
            fila[5] = usuario.getCedula();

            modeloTabla.addRow(fila);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnModificar2 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnEliminarSolicitud = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnAgregar.setText("Agregar Vendedor");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar VENDEDOR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tblUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Id", "Nombre", "Correo", "Contraseña", "TipoUsuario", "Cedula"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblUsuario.setMinimumSize(new java.awt.Dimension(45, 0));
        tblUsuario.setPreferredSize(new java.awt.Dimension(225, 0));
        tblUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsuario.setShowHorizontalLines(false);
        tblUsuario.setShowVerticalLines(false);
        tblUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblUsuarioFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);
        tblUsuario.getColumnModel().getSelectionModel()
                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnModificar2.setText("Modificar COMPRADOR");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Agregar Comprador");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        tblSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        tblSolicitudes.setForeground(new java.awt.Color(0, 0, 0));
        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Solicitudes"
                }) {
            boolean[] canEdit = new boolean[] {
                    false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblSolicitudes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSolicitudes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSolicitudes.setShowHorizontalLines(false);
        tblSolicitudes.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tblSolicitudes);

        btnEliminarSolicitud.setText("Eliminar Solicitud");
        btnEliminarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSolicitudActionPerformed(evt);
            }
        });

        btnEliminar2.setText("Eliminar TODAS las Solicitudes");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAgregar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAgregar1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnModificar2)
                                                .addGap(331, 331, 331)
                                                .addComponent(btnEliminar)
                                                .addGap(29, 29, 29)
                                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(126, 126, 126))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane4,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 1359,
                                                                Short.MAX_VALUE))
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarSolicitud)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 224,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnAgregar)
                                                                .addComponent(btnModificar)
                                                                .addComponent(btnEliminar)
                                                                .addComponent(btnSalir)
                                                                .addComponent(btnModificar2)
                                                                .addComponent(btnAgregar1))
                                                        .addComponent(jSeparator1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 212,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEliminar2))
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminarSolicitud))
                                .addContainerGap(147, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        FrmRegistrarVendedor oFrmRegistrarUsuario = new FrmRegistrarVendedor(TipoMantenimiento.AGREGAR, null);
        oFrmRegistrarUsuario.setVisible(true);
        oFrmRegistrarUsuario.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                llenarTabla();
            }
        });

    }

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (tblUsuario.getSelectedRow() >= 0) {

                int id = (int) modeloTabla.getValueAt(tblUsuario.getSelectedRow(), 0);

                oUsuario = PersistenciaUsuarioTabla.getUsuario(id);

                if (oUsuario != null) {

                    FrmRegistrarVendedor oFrmRegistrarUsuario = new FrmRegistrarVendedor(TipoMantenimiento.MODIFICAR,
                            oUsuario);
                    oFrmRegistrarUsuario.setAlwaysOnTop(true);
                    oFrmRegistrarUsuario.setVisible(true);

                    oFrmRegistrarUsuario.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            llenarTabla();
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "Error: No se encontró el usuario.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para modificar.");
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del usuario: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                if (tblUsuario.getSelectedRow() >= 0) {

                    int id = (int) modeloTabla.getValueAt(tblUsuario.getSelectedRow(), 0);

                    PersistenciaUsuarioTabla.eliminarUsuario(id);

                    llenarTabla();

                } else {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.");
                }
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del usuario: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }

    }

    private void tblUsuarioFocusGained(java.awt.event.FocusEvent evt) {
    }

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (tblUsuario.getSelectedRow() >= 0) {

                int id = (int) modeloTabla.getValueAt(tblUsuario.getSelectedRow(), 0);

                oUsuario = PersistenciaUsuarioTabla.getUsuario(id);

                if (oUsuario != null) {

                    FrmRegistrarVendedor oFrmRegistrarVendedor = new FrmRegistrarVendedor(TipoMantenimiento.MODIFICAR,
                            oUsuario);
                    oFrmRegistrarVendedor.setAlwaysOnTop(true);
                    oFrmRegistrarVendedor.setVisible(true);

                    oFrmRegistrarVendedor.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            llenarTabla();
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "Error: No se encontró el usuario.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un Vendedor para modificar.");
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del usuario: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }

    }

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {
        FrmRegistrarComprador RegistrarVendedor = new FrmRegistrarComprador(TipoMantenimiento.AGREGAR, null);
        RegistrarVendedor.setVisible(true);
        RegistrarVendedor.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                llenarTabla();
            }
        });

    }

    private void btnEliminarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea eliminar esta Solicitud de Vendedor?", "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                if (tblSolicitudes.getSelectedRow() >= 0) {

                    int id = (int) modeloTabla.getValueAt(tblSolicitudes.getSelectedRow(), 0);

                    PersistenciaSolicitudUsuario.eliminarSolicitud(id);

                    llenarTabla();

                } else {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.");
                }
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del usuario: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Error Opcion bloqueada temporalmente ");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminarSolicitud;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTable tblUsuario;
    // End of variables declaration
}

class FondoTabla extends JPanel {
    private ImageIcon tabla;

    public FondoTabla() {

        tabla = new ImageIcon(
                "C:\\Users\\Iván Monjarrez\\proyecto-web\\src\\main\\java\\entidades\\imagenes\\imagenes\\file-Ab8M8ofQyKkgoWFJj8LMxq.jpg");
        if (tabla.getImageLoadStatus() != MediaTracker.COMPLETE) {
            System.err.println("Error al cargar la imagen de fondo.");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (tabla != null) {
            g.drawImage(tabla.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    }

}
