package entidades.appMonjarrez;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Iván Monjarrez
 */
public class MDI_MenuMonjarrez extends javax.swing.JFrame {
      private FrmTablaUsuario oFrmTablaUsuario;    
          
    /**
     * Creates new form MDI_MenuMonjarrez
     */
    public MDI_MenuMonjarrez() {
        initComponents();
    }
    
    
    
   
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        LblRegistrarmecomo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnSistema = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnMantenimiento = new javax.swing.JMenu();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        mnProcesos = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnProcesos1 = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setOpaque(false);

        LblRegistrarmecomo.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        //LblRegistrarmecomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/bienvenido-de-nuevo.png"))); // NOI18N
        LblRegistrarmecomo.setText("Administrar Cartelera");
        desktopPane.add(LblRegistrarmecomo);
        LblRegistrarmecomo.setBounds(10, 10, 330, 64);

       // jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/tendencia (1).png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(510, 300, 630, 540);

        mnSistema.setMnemonic('f');
        mnSistema.setText("Sistema");

        mniSalir.setMnemonic('x');
        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnSistema.add(mniSalir);

        menuBar.add(mnSistema);

        mnMantenimiento.setMnemonic('e');
        mnMantenimiento.setText("Mantenimiento");

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Usuarios");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        mnMantenimiento.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Personal");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        mnMantenimiento.add(pasteMenuItem);

        menuBar.add(mnMantenimiento);

        mnProcesos.setMnemonic('h');
        mnProcesos.setText("Procesos");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        mnProcesos.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        mnProcesos.add(aboutMenuItem);

        menuBar.add(mnProcesos);

        mnProcesos1.setMnemonic('h');
        mnProcesos1.setText("Ayuda");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Contactos");
        mnProcesos1.add(contentMenuItem1);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("Sugerencias");
        aboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem1ActionPerformed(evt);
            }
        });
        mnProcesos1.add(aboutMenuItem1);

        menuBar.add(mnProcesos1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
      formWindowClosing(new WindowEvent(this,0));

    }                                        

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
      if (oFrmTablaUsuario == null) {
        oFrmTablaUsuario = new FrmTablaUsuario(); 
        desktopPane.add(oFrmTablaUsuario); 
    }
    
    oFrmTablaUsuario.setVisible(true); 
    oFrmTablaUsuario.toFront(); 
      
        
        //FrmTablaUsuario oFrmTablaUsuario = new FrmTablaUsuario();
    //oFrmTablaUsuario.setExtendedState(JFrame.MAXIMIZED_BOTH);
       // oFrmTablaUsuario.setVisible(true);
    
    }                                            

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                              
    }                                             

    private void aboutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
    }                                              

    
    
    
    
    
    // private void someActionToOpenSolicitudDeVendedor() {
    //     if (oFrmTablaUsuario != null) {
    //         FrmSolicitudDeVendedor frmSolicitudDeVendedor = new FrmSolicitudDeVendedor(oFrmTablaUsuario);
    //         frmSolicitudDeVendedor.setVisible(true);
    //     } else {
    //         JOptionPane.showMessageDialog(this, "Error: La referencia a FrmTablaUsuario es nula.");
    //     }
    // }
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea abandonar el área de Configuraciones?",
                "Atención",JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }       
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI_MenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI_MenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI_MenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI_MenuMonjarrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI_MenuMonjarrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel LblRegistrarmecomo;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnMantenimiento;
    private javax.swing.JMenu mnProcesos;
    private javax.swing.JMenu mnProcesos1;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration                   

    

}

